"""Type stub for the `_pyjutsu` native extension (the thin PyO3 layer).

The extension returns plain data; the pure-Python package validates/wraps it. Keep this stub
in sync with `src/`.
"""

from __future__ import annotations

import os

class PyjutsuError(Exception):
    """Base class for errors raised by the native layer."""

class RevsetError(PyjutsuError):
    """A revset failed to parse, resolve, or evaluate."""

class ConflictError(PyjutsuError):
    """A conflict blocked an operation."""

class BackendError(PyjutsuError):
    """The underlying store/backend reported an error."""

class WorkspaceError(PyjutsuError):
    """A workspace could not be loaded or is unusable."""

class WorkingCopyError(PyjutsuError):
    """The working copy could not be locked, snapshotted, or checked out."""

class StaleWorkingCopyError(WorkingCopyError):
    """The working copy is stale (another operation moved ``@``)."""

class ImmutableCommitError(PyjutsuError):
    """An attempt was made to rewrite or abandon an immutable commit (e.g. the root)."""

class GitError(BackendError):
    """A git import/export or remote operation failed."""

def version() -> str:
    """Return the jj-lib version this extension was built against (build-derived, e.g. ``"0.42.0"``)."""

def pyjutsu_version() -> str:
    """Return the compiled pyjutsu crate version (``CARGO_PKG_VERSION``), for the stale-build guard."""

class PyRepoView:
    """Opaque handle to a ReadonlyRepo at one operation, scoped to a workspace."""

    def working_copy(self) -> dict[str, object]: ...
    def resolve(self, revset_str: str) -> dict[str, object]: ...
    def log(self, revset_str: str, limit: int | None = ...) -> list[dict[str, object]]: ...
    def log_stream(self, revset_str: str, limit: int | None = ...) -> PyCommitStream: ...
    def operations(self, limit: int | None = ...) -> list[dict[str, object]]: ...
    def operation_id(self) -> str: ...
    def bookmarks(self) -> list[dict[str, object]]: ...
    def conflicts(self, revset_str: str) -> list[dict[str, object]]: ...
    def diff_stat(self, revset_str: str) -> dict[str, object]: ...
    def diff(self, revset_str: str) -> dict[str, object]: ...

class PyCommitStream:
    """One-shot iterator yielding a revset's commits as plain dicts, built one per step."""

    def __iter__(self) -> PyCommitStream: ...
    def __next__(self) -> dict[str, object]: ...

class PyWorkspace:
    """Opaque handle to one jj workspace (one working-copy path)."""

    @staticmethod
    def load(path: str | os.PathLike[str]) -> PyWorkspace: ...
    @staticmethod
    def init(path: str | os.PathLike[str], colocate: bool = ...) -> PyWorkspace: ...
    def add_workspace(
        self, path: str | os.PathLike[str], name: str | None = ...
    ) -> dict[str, object]: ...
    def forget_workspace(self, name: str) -> None: ...
    def workspaces(self) -> list[dict[str, object]]: ...
    def name(self) -> str: ...
    def workspace_root(self) -> str: ...
    def head_view(self) -> PyRepoView: ...
    def head_operation(self) -> str: ...
    def at_operation(self, op_str: str) -> PyRepoView: ...
    def snapshot(self) -> dict[str, object] | None: ...
    def untrack_paths(self, paths: list[str]) -> dict[str, object] | None: ...
    def is_stale(self) -> bool: ...
    def update_stale(self) -> dict[str, object] | None: ...
    def undo(self, operation: str | None = ...) -> dict[str, object]: ...
    def restore_operation(self, operation: str) -> dict[str, object]: ...
    def git_import(self) -> dict[str, object] | None: ...
    def git_export(self) -> dict[str, object] | None: ...
    def sync_colocated(self) -> dict[str, object] | None: ...
    def git_fetch(
        self, remote: str, bookmarks: list[str] | None = ...
    ) -> dict[str, object] | None: ...
    def git_push(
        self,
        remote: str,
        bookmarks: list[str],
        allow_new: bool = ...,
        delete: bool = ...,
        all: bool = ...,
        tracked: bool = ...,
    ) -> dict[str, object] | None: ...
    def git_default_branch(self, remote: str) -> str | None: ...
    def remotes(self) -> list[dict[str, object]]: ...
    def add_remote(self, name: str, url: str) -> None: ...
    def remove_remote(self, name: str) -> None: ...
    def rename_remote(self, old: str, new: str) -> None: ...
    def set_remote_url(self, name: str, url: str) -> None: ...
    def begin_transaction(self) -> PyTransaction: ...

class PyTransaction:
    """Opaque, single-thread-bound handle to one in-flight jj transaction."""

    def describe(self, revset_str: str, message: str) -> dict[str, object]: ...
    def new(self, parents: list[str] | None = ...) -> dict[str, object]: ...
    def edit(self, revset_str: str) -> dict[str, object]: ...
    def abandon(self, revset_str: str) -> None: ...
    def rebase(
        self, commit: str, onto: list[str], mode: str = ...
    ) -> dict[str, object]: ...
    def squash(self, source: str, into: str, message: str | None = ...) -> dict[str, object]: ...
    def restore(
        self, commit: str, from_: str, paths: list[str] | None = ...
    ) -> dict[str, object]: ...
    def select_tree(
        self, commit: str, selection: dict[str, list[int] | None]
    ) -> str: ...
    def split(
        self, commit: str, selection: dict[str, list[int] | None], mode: str = ...
    ) -> tuple[dict[str, object], dict[str, object]]: ...
    def create_bookmark(self, name: str, commit: str) -> dict[str, object]: ...
    def set_bookmark(self, name: str, commit: str) -> dict[str, object]: ...
    def delete_bookmark(self, name: str) -> None: ...
    def track_bookmark(self, name: str, remote: str) -> dict[str, object]: ...
    def untrack_bookmark(self, name: str, remote: str) -> dict[str, object]: ...
    def commit(self, description: str) -> str: ...
    def rollback(self) -> None: ...
